services:
  php:
    build:
      context: ./
      dockerfile: PHP/Dockerfile
    container_name: api-companies
    restart: "no"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: PostgreSQL/Dockerfile
    container_name: api-companies-postgres
    restart: "no"
    environment:
      - POSTGRES_DB=api_companies
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/data/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres:
  